# git에서 제거하기
server:
  url: https://3.34.129.72.nip.io

spring:
  datasource:
    url: jdbc:mysql://${RDS_HOST}:${RDS_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true

  data:
    redis:
      host: gymmate-deploy-redis
      port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-disabled: false

logging:
  level:
    org.helloworld.gymmate: DEBUG
