services:
  mysql:
    image: mysql:latest
    container_name: gymmate-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gymmate_db
      MYSQL_USER: gymmate_user
      MYSQL_PASSWORD: gymmate_password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    networks:
      - gymmate-network
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: gymmate-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - gymmate-network
    volumes:
      - redis_data:/data

networks:
  gymmate-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
